apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: info@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [development]

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: mock-users
  description: A collection of all example Groups
spec:
  targets:
    - ./groups-users.yaml